# 张量
张量是一种与数组和矩阵非常相似的专门数据结构。在 PyTorch 中，我们使用张量对模型的输入和输出以及模型的参数进行编码。

张量类似于 NumPy 的 ndarrays，但张量可以在 GPU 或其他硬件加速器上运行。事实上，张量和 NumPy 数组通常可以共享相同的底层内存，从而无需复制数据（请参阅 与 NumPy 的桥梁）。张量还针对自动微分进行了优化（我们将在 自动微分 部分中详细了解）。如果您熟悉 ndarrays，那么您将非常熟悉张量 API。如果不熟悉，请继续关注！

In [1]:
import torch
import numpy as np

# 初始化张量
张量可以通过多种方式初始化。请看以下示例

## 直接从数据
张量可以直接从数据创建。数据类型会自动推断。

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data.shape)

torch.Size([2, 2])


## 从 NumPy 数组
张量可以从 NumPy 数组创建（反之亦然 - 请参阅 与 NumPy 之间的桥梁）。

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np.shape)

torch.Size([2, 2])


## 从另一个张量
新张量保留参数张量的属性（形状、数据类型），除非明确覆盖。

In [4]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Ones Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Ones Tensor: 
 tensor([[0.0161, 0.8131],
        [0.2941, 0.6802]]) 



## 使用随机值或者常量值
shape是张量维度的元祖。在以下函数中，它决定输出张量的维度。

In [5]:
shape = (1,2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[[0.0729, 0.1844, 0.8917],
         [0.9720, 0.4820, 0.5201]]]) 

Ones Tensor: 
 tensor([[[1., 1., 1.],
         [1., 1., 1.]]]) 

Zeros Tensor: 
 tensor([[[0., 0., 0.],
         [0., 0., 0.]]])


# 张量的属性
超过 100 种张量操作，包括算术、线性代数、矩阵操作（转置、索引、切片）、采样等，在此处 进行了全面描述。

这些操作中的每一个都可以在 GPU 上运行（速度通常高于 CPU）。如果你正在使用 Colab，请通过转到运行时 > 更改运行时类型 > GPU 来分配一个 GPU。

默认情况下，张量是在 CPU 上创建的。我们需要使用 .to 方法（在检查 GPU 可用性后）将张量显式地移动到 GPU。请记住，跨设备复制大张量在时间和内存方面可能是昂贵的！

In [6]:
# We move our tensor to the GPU if available
shape = (1,1024,1024,1024)
tensor = torch.rand(shape)
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

# # Remove tensor in cuda device
# del tensor
# torch.cuda.empty_cache()

# 张量操作
超过 100 个张量操作，包括转置、索引、切片、数学运算、线性代数、随机采样等，在此处进行了全面描述此处。

每个操作都可以在 GPU 上运行（速度通常高于 CPU）。如果你正在使用 Colab，请转到编辑 > 笔记本设置来分配 GPU。

In [7]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

尝试列表中的部分操作。如果您熟悉 NumPy API，您会发现 Tensor API 非常容易使用。

## 标准 numpy 式索引和切片

In [8]:
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


连接张量您可以使用 torch.cat 沿给定维度连接一系列张量。另请参阅 torch.stack，另一个张量连接操作，与 torch.cat 略有不同。

In [9]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


## 相乘张量

In [10]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


这计算两个张量之间的矩阵乘法

In [11]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


就地操作带有 _ 后缀的操作是就地的。例如：x.copy_(y)、x.t_()，将更改 x。

In [12]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
